-- ============================================================
-- ChispaApp - setup.sql
-- Ejecutar este script en el SQL Editor de Supabase
-- para crear toda la estructura de la base de datos.
-- ============================================================


-- ============================================================
-- 1. USUARIOS (alumnos)
-- ============================================================
create table if not exists users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  nombre text not null,
  grado text,                            -- Ej: "1", "2", ... "6"
  estilo_aprendizaje text                -- 'Visual' | 'Auditivo' | 'Kinestesico'
);

alter table users enable row level security;
create policy "Allow all on users" on users for all using (true);


-- ============================================================
-- 2. MATERIAS
-- ============================================================
create table if not exists subjects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  nombre text not null,                  -- Ej: "Matemáticas", "Español"
  descripcion text,
  nivel text                             -- Ej: "Básico", "Intermedio", "Avanzado"
);

alter table subjects enable row level security;
create policy "Allow all on subjects" on subjects for all using (true);


-- ============================================================
-- 3. LECCIONES (contenido adaptado al estilo VAK)
-- ============================================================
create table if not exists lessons (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  subject_id bigint references subjects(id) on delete cascade,
  titulo text not null,
  contenido_visual text,                 -- Texto o URL de imagen para estilo Visual
  contenido_auditivo text,               -- URL de audio para estilo Auditivo
  contenido_kinestesico text,            -- Descripción de actividad para Kinestésico
  nivel text                             -- Ej: "1", "2", "3"
);

alter table lessons enable row level security;
create policy "Allow all on lessons" on lessons for all using (true);


-- ============================================================
-- 4. PROGRESO DEL ALUMNO POR MATERIA
-- ============================================================
create table if not exists progress (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  user_id bigint references users(id) on delete cascade,
  subject_id bigint references subjects(id) on delete cascade,
  porcentaje_avance integer default 0,   -- 0 a 100
  puntuacion integer default 0,
  racha integer default 0                -- Días consecutivos estudiando
);

alter table progress enable row level security;
create policy "Allow all on progress" on progress for all using (true);


-- ============================================================
-- 5. RESULTADOS DEL QUIZ VAK
-- ============================================================
create table if not exists vak_results (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  user_id bigint references users(id) on delete cascade,
  puntaje_visual integer default 0,
  puntaje_auditivo integer default 0,
  puntaje_kinestesico integer default 0,
  estilo_dominante text                  -- 'Visual' | 'Auditivo' | 'Kinestesico'
);

alter table vak_results enable row level security;
create policy "Allow all on vak_results" on vak_results for all using (true);


-- ============================================================
-- 6. RECOMPENSAS / LOGROS
-- ============================================================
create table if not exists rewards (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  user_id bigint references users(id) on delete cascade,
  titulo text not null,                  -- Ej: "¡Racha de 7 días!"
  xp_ganado integer default 0,
  estrellas integer default 0,           -- 1 a 3
  lesson_id bigint references lessons(id) on delete set null
);

alter table rewards enable row level security;
create policy "Allow all on rewards" on rewards for all using (true);
